name: AACL-IJCNLP 2020
tagline: The 1st Conference of the Asia-Pacific Chapter of the Association for <br> Computational Linguistics and the 10th International Joint Conference on Natural Language Processing 
date: December 4 &ndash; 7 <br> 2020
proceedings_title: Proceedings of the 58th Annual Meeting of the Association for Computational Linguistics
citation_date: July 2020
analytics: UA-171494682-1
site_url: https://virtual.acl2020.org
logo:
  image: static/images/aacl2020/AACLlogo.png
  image1: static/images/aacl2020/AFNLPlogo.png
  height: 45px
site_title: AACL-IJCNLP 2020
page_title:
  prefix: 'AACL-IJCNLP 2020'
  separator: ': '
background_image: static/images/aacl2020/banner.jpg
organization: Association for Computational Linguistics

# Path to the folder of paper images.
paper_images_path: https://acl2020-public.s3.amazonaws.com/papers
default_presentation_id: 38931484

# Remove or change to your chat server.
chat_server: acl2020.rocket.chat

calendar:
  start: '2020-07-05'
  end: '2020-07-10'
